version: 2

builds:
  - main: ./cmd/yaz
    binary: yaz
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  - repository:
      owner: ilkin0
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/ilkin0/yaz"
    description: "Terminal UI tool for flashing OS images to USB drives"
    license: "MIT"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
